name: Build and deploy AngularWebApp to Storage Container

concurrency:
  group: deployAngularWebApp
  cancel-in-progress: true

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: npx nx run-many -t build
      # - run: npx nx affected --parallel 1 -t e2e-ci

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: nxbuild
          path: dist/apps

  deployAngularWebApp:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: nxbuild

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.ANGULAR_WEB_APP_SECRET }}

      - name: Clear destination
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch --account-name angularwebapp --auth-mode key -s 'web'

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --overwrite --account-name angularwebapp --auth-mode key -d 'web' -s 'angularwebapp/browser'

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
  deployAngularWebApp2:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: nxbuild

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.ANGULAR_WEB_APP_SECRET }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'angularwebapp2'
          slot-name: 'production'
          package: /angularwebapp2/browser

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
